name: Sync Release Branch

on:
  push:
    branches:
      - main

jobs:
  sync-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update or create release branch
        run: |
          if git ls-remote --exit-code --heads origin release; then
            git fetch origin release
            git checkout -b release origin/release
            git merge --no-edit origin/main
          else
            git checkout -b release
          fi

          git push origin release
